site_name: Pydantic2
site_description: A powerful Python framework for building AI applications with structured responses powered by Pydantic AI
site_url: https://pydantic.unrealos.com
repo_url: https://github.com/markolofsen/pydantic2
repo_name: markolofsen/pydantic2

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  logo: assets/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - footnotes
  - tables

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - Core Concepts:
    - Message Handling: core-concepts/message-handling.md
    - Type-Safe Responses: core-concepts/type-safe-responses.md
    - Usage & Cost:
      - Overview: core-concepts/usage/info.md
      - Model Pricing: core-concepts/usage/model-pricing.md
      - Request Tracking: core-concepts/usage/request-tracking.md
    - Online Search: core-concepts/online-search.md
    - Budget Management: core-concepts/budget-management.md
    - Error Handling: core-concepts/error-handling.md
  - Agents:
    - Progress Form: agents/progress-form.md
  - Integrations:
    - Django REST: integrations/django-drf.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Chat Completion: examples/chat-completion.md
    - Agent Progress Form: examples/agent-progress-form.md
  - CLI Tools: cli.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
            docstring_style: google
  - git-revision-date-localized:
      type: datetime
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/markolofsen/pydantic2
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pydantic2
    - icon: fontawesome/solid/globe
      link: https://unrealos.com

copyright: Copyright &copy; 2025 UnrealOS
site_dir: site
